# Generated by Django 5.2.6 on 2025-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
                ('category', models.TextField()),
                ('imgs', models.ImageField(default='static/images/default.jpg', upload_to='static/images/')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
