# Generated by Django 5.2.6 on 2025-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bui',
            name='descrip',
        ),
    ]
