# Generated by Django 5.2.6 on 2025-09-30 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_bui_descrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bui',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='bui',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
